# This file is generated by scripts/generate_autopkg_processor_versions.py.
# Do not edit it by hand.

PROC_VERSIONS = {
    "AppDmgVersioner": {
        "_introduced_": "0.1.0",
    },
    "AppPkgCreator": {
        "_introduced_": "1.0",
        "version_key": "2.4.1",
    },
    "BrewCaskInfoProvider": {
        "_introduced_": "0.2.5",
        "_removed_": "2.9.0",
    },
    "CURLDownloader": {
        "_introduced_": "0.5.1",
        "_deprecated_": "0.6.0",
        "_removed_": "3.0.0",
    },
    "CURLTextSearcher": {
        "_introduced_": "0.5.1",
        "_deprecated_": "0.6.0",
        "_removed_": "3.0.0",
    },
    "ChocolateyPackager": {
        "_introduced_": "2.3",
    },
    "CodeSignatureVerifier": {
        "_introduced_": "0.3.1",
        "DISABLE_CODE_SIGNATURE_VERIFICATION": "0.4.2",
        "codesign_additional_arguments": "1.0.3",
        "deep_verification": "1.0.3",
        "requirement": "0.4.1",
        "strict_verification": "1.0.3",
    },
    "Copier": {
        "_introduced_": "0.1.0",
    },
    "DeprecationWarning": {
        "_introduced_": "1.1",
    },
    "DmgCreator": {
        "_introduced_": "0.1.0",
        "dmg_filesystem": "1.0.3",
        "dmg_format": "0.3.0",
        "dmg_megabytes": "0.3.0",
        "dmg_zlib_level": "0.3.0",
    },
    "DmgMounter": {
        "_introduced_": "0.1.0",
    },
    "EndOfCheckPhase": {
        "_introduced_": "0.1.0",
    },
    "FileCreator": {
        "_introduced_": "0.1.0",
        "file_mode": "0.5.0",
    },
    "FileFinder": {
        "_introduced_": "0.2.3",
    },
    "FileMover": {
        "_introduced_": "0.2.9",
    },
    "FindAndReplace": {
        "_introduced_": "2.7.6",
    },
    "FlatPkgPacker": {
        "_introduced_": "0.2.4",
    },
    "FlatPkgUnpacker": {
        "_introduced_": "0.1.0",
    },
    "GitHubReleasesInfoProvider": {
        "_introduced_": "0.5.0",
        "CURL_PATH": "1.4",
        "GITHUB_RELEASES_PER_PAGE": "2.9.0",
        "GITHUB_TOKEN_PATH": "2.3",
        "GITHUB_URL": "2.3",
        "curl_opts": "1.4",
        "latest_only": "2.7.1",
    },
    "InstallFromDMG": {
        "_introduced_": "0.4.0",
    },
    "Installer": {
        "_introduced_": "0.4.0",
    },
    "MunkiCatalogBuilder": {
        "_introduced_": "0.1.0",
        "_deprecated_": "2.7.5",
    },
    "MunkiImporter": {
        "_introduced_": "0.1.0",
        "MUNKILIB_DIR": "2.2",
        "MUNKI_PKGINFO_FILE_EXTENSION": "0.3.0",
        "MUNKI_REPO": "0.2.5",
        "MUNKI_REPO_PLUGIN": "2.2",
        "extract_icon": "2.2",
        "force_munki_repo_lib": "2.2",
        "metadata_additions": "1.1",
        "uninstaller_pkg_path": "1.0.0",
        "version_comparison_key": "0.3.0",
    },
    "MunkiInfoCreator": {
        "_introduced_": "0.1.0",
    },
    "MunkiInstallsItemsCreator": {
        "_introduced_": "0.1.0",
        "derive_minimum_os_version": "2.6",
        "version_comparison_key": "0.3.0",
    },
    "MunkiOptionalReceiptEditor": {
        "_introduced_": "2.7",
    },
    "MunkiPkginfoMerger": {
        "_introduced_": "0.1.0",
    },
    "MunkiSetDefaultCatalog": {
        "_introduced_": "0.4.2",
    },
    "PackageRequired": {
        "_introduced_": "0.5.1",
    },
    "PathDeleter": {
        "_introduced_": "0.1.0",
    },
    "PkgCopier": {
        "_introduced_": "0.1.0",
    },
    "PkgCreator": {
        "_introduced_": "0.1.0",
        "force_pkg_build": "0.3.0",
    },
    "PkgExtractor": {
        "_introduced_": "0.1.0",
    },
    "PkgInfoCreator": {
        "_introduced_": "0.1.0",
    },
    "PkgPayloadUnpacker": {
        "_introduced_": "0.1.0",
    },
    "PkgRootCreator": {
        "_introduced_": "0.1.0",
    },
    "PlistEditor": {
        "_introduced_": "0.1.0",
    },
    "PlistReader": {
        "_introduced_": "0.2.5",
    },
    "SignToolVerifier": {
        "_introduced_": "2.3",
    },
    "SparkleUpdateInfoProvider": {
        "_introduced_": "0.1.0",
        "CURL_PATH": "0.6.0",
        "PKG": "0.5.0",
        "curl_opts": "1.4",
        "update_channel": "2.7.1",
        "urlencode_path_component": "1.1",
    },
    "StopProcessingIf": {
        "_introduced_": "0.1.0",
    },
    "Symlinker": {
        "_introduced_": "0.1.0",
    },
    "URLDownloader": {
        "_introduced_": "0.1.0",
        "CHECK_FILESIZE_ONLY": "0.6.0",
        "CURL_PATH": "0.6.0",
        "curl_opts": "1.0.4",
        "prefetch_filename": "1.4",
    },
    "URLDownloaderPython": {
        "_introduced_": "2.4.1",
        "request_headers": "2.9.0",
    },
    "URLGetter": {
        "_introduced_": "1.4",
    },
    "URLTextSearcher": {
        "_introduced_": "0.2.9",
        "CURL_PATH": "0.6.0",
        "curl_opts": "1.0.4",
    },
    "Unarchiver": {
        "_introduced_": "0.1.0",
        "USE_PYTHON_NATIVE_EXTRACTOR": "2.3",
    },
    "VariableSetter": {
        "_introduced_": "2.9.0",
    },
    "Versioner": {
        "_introduced_": "0.1.0",
        "skip_single_root_dir": "2.3",
    },
}

GENERATION_METADATA = {
    "generator_version": 2,
    "last_walked_ref": "v2.9.0",
    "last_walked_version": "2.9.0",
    "source": "https://github.com/autopkg/autopkg",
}
