#!/usr/bin/python
"""This hook checks AutoPkg recipes to ensure they meet various
requirements."""

import argparse
import contextlib
import os
import sys
from typing import Any

from packaging.version import InvalidVersion, Version

from pre_commit_macadmin_hooks.autopkg_processor_versions import PROC_VERSIONS
from pre_commit_macadmin_hooks.util import (
    detect_deprecated_keys,
    detect_typoed_keys,
    load_autopkg_recipe,
    validate_pkginfo_key_types,
    validate_required_keys,
    validate_restart_action_key,
    validate_supported_architectures,
    validate_uninstall_method,
)

# Import AutoPkg libraries, but ignore any warnings generated by the import.
sys.path.append("/Library/AutoPkg")
try:
    with open(os.devnull, "w", encoding="utf-8") as devnull, contextlib.redirect_stdout(
        devnull
    ):
        from autopkglib import (  # type: ignore[import-not-found]
            get_processor,
            processor_names,
        )

    HAS_AUTOPKGLIB = True
except ImportError:
    # Silently skip checks that require autopkglib.
    HAS_AUTOPKGLIB = False

if HAS_AUTOPKGLIB:
    _CORE_PROCS = {
        proc: getattr(get_processor(proc), "input_variables", {})
        for proc in processor_names()
    }
else:
    _CORE_PROCS = {}


def build_argument_parser() -> argparse.ArgumentParser:
    """Build and return the argument parser."""

    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--override-prefix",
        nargs="+",
        default=["local."],
        help='Expected prefix(es) for recipe override identifiers (defaults to ["local."]). '
        "Case sensitive. Multiple acceptable identifier prefixes can be provided.",
    )
    parser.add_argument(
        "--recipe-prefix",
        nargs="+",
        default=["com.github."],
        help='Expected prefix(es) for recipe identifiers (defaults to ["com.github."]). '
        "Case sensitive. Multiple acceptable identifier prefixes can be provided.",
    )
    parser.add_argument(
        "--ignore-min-vers-before",
        default="1.0",
        help="Ignore MinimumVersion/processor mismatches below this version of AutoPkg "
        '(defaults to "1.0").\nSet to 0.1.0 to warn about all '
        "MinimumVersion/processor mismatches.\nDefaults to 0.1.0 if --strict is used.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        default=False,
        help="Apply strictest set of rules when evaluating AutoPkg recipes, including "
        "adherence to recipe type conventions, flagging all MinimumVersion/processor "
        "mismatches, and forbidding <!-- --> comments. Very opinionated.",
    )
    parser.add_argument("filenames", nargs="*", help="Filenames to check.")
    return parser


def validate_recipe_prefix(
    recipe: dict[str, Any], filename: str, prefix: list[str]
) -> bool:
    """Verify that the recipe identifier starts with the expected prefix."""

    passed = True
    if not any(recipe["Identifier"].startswith(x) for x in prefix):
        print(
            "{}: identifier does not start with {}".format(
                filename,
                (
                    'one of: "%s"' % '", "'.join(prefix)
                    if len(prefix) > 1
                    else prefix[0]
                ),
            )
        )
        passed = False

    return passed


def validate_comments(filename, strict):
    """Warn about comments in <!-- --> format that would break when running
    plutil -convert xml1."""

    passed = True
    with open(filename, encoding="utf-8") as openfile:
        recipe_text = openfile.read()
        if "<!--" in recipe_text and "-->" in recipe_text:
            if strict:
                print(
                    f"{filename}: Convert from <!-- --> style comments to a Comment key."
                )
                passed = False
            else:
                print(
                    f"{filename}: WARNING: Recommend converting from <!-- --> style comments "
                    "to a Comment key."
                )

    return passed


def validate_processor_keys(process, filename):
    """Ensure all items in Process array have a "Processor" specified."""

    passed = True
    missing_processor_keys = [x for x in process if "Processor" not in x]
    if missing_processor_keys:
        for missing_proc in missing_processor_keys:
            print(
                f'{filename}: Item in processor array is missing "Processor" key:\n{missing_proc}'
            )
        passed = False

    return passed


def validate_endofcheckphase(process, filename):
    """Ensure EndOfCheckPhase comes after a downloader."""

    passed = True
    downloader_idx = next(
        (
            idx
            for (idx, x) in enumerate(process)
            if x.get("Processor") in ("URLDownloader", "URLDownloaderPython")
        ),
        None,
    )
    if downloader_idx is None:
        return passed
    endofcheck_idx = next(
        (
            idx
            for (idx, x) in enumerate(process)
            if x.get("Processor") == "EndOfCheckPhase"
        ),
        None,
    )
    if endofcheck_idx is None:
        print(
            f"{filename}: Contains a download processor, but no EndOfCheckPhase processor."
        )
        passed = False
    elif endofcheck_idx < downloader_idx:
        print(
            f"{filename}: EndOfCheckPhase typically goes after a download processor, not before."
        )
        passed = False

    return passed


def validate_minimumversion(process, min_vers, ignore_min_vers_before, filename):
    """Ensure MinimumVersion is a string and is set appropriately for the
    processors used."""

    passed = True

    # Validate that the MinimumVersion value is a string
    if not isinstance(min_vers, str):
        print(f"{filename}: MinimumVersion should be a string.")
        return False

    # Validate that the MinimumVersion value is a parseable version string.
    try:
        min_vers_version = Version(min_vers)
    except InvalidVersion:
        print(f"{filename}: MinimumVersion {min_vers!r} is not a valid version string.")
        return False

    # Validate that the MinimumVersion value fits the processors and processor
    # arguments used. Unknown processors and unknown arguments fail open.
    for proc in process:
        proc_name = proc.get("Processor")
        proc_versions = PROC_VERSIONS.get(proc_name)
        if proc_versions is None:
            continue

        proc_min_version = proc_versions.get("_introduced_")
        if proc_min_version is None:
            continue

        required_version = proc_min_version
        required_arg = None
        for arg in proc.get("Arguments", {}):
            arg_min_version = proc_versions.get(arg)
            if arg_min_version and Version(arg_min_version) > Version(required_version):
                required_version = arg_min_version
                required_arg = arg

        if Version(required_version) < Version(ignore_min_vers_before):
            continue

        if min_vers_version < Version(required_version):
            what = (
                f"{proc_name} {required_arg} argument"
                if required_arg
                else f"{proc_name} processor"
            )
            print(
                f"{filename}: {what} requires minimum AutoPkg version {required_version}"
            )
            passed = False

    return passed


def validate_no_deprecated_procs(process, filename):
    """Error on removed processors; warn on deprecated ones."""

    passed = True
    for proc in process:
        name = proc.get("Processor")
        proc_versions = PROC_VERSIONS.get(name)
        if proc_versions is None:
            continue

        removed_version = proc_versions.get("_removed_")
        deprecated_version = proc_versions.get("_deprecated_")
        if removed_version:
            print(
                f"{filename}: Processor {name} was removed in AutoPkg {removed_version}."
            )
            passed = False
        elif deprecated_version:
            print(
                f"{filename}: WARNING: Processor {name} was deprecated in AutoPkg "
                f"{deprecated_version}."
            )

    return passed


def validate_no_superclass_procs(process, filename):
    """Warn if any superclass processors (which are used by other processors
    rather than called in recipes) are used."""

    # Processors that are superclasses and shouldn't be referenced directly.
    superclass_procs = ("URLGetter",)

    passed = True
    for proc in process:
        if proc.get("Processor") in superclass_procs:
            print(
                f"{filename}: WARNING: The processor {proc.get('Processor')} is intended to be used "
                "by other processors, not used directly in recipes."
            )

    return passed


def validate_jamf_processor_order(process, filename):
    """Warn if JamfUploader processors are not in their conventional order.
    https://youtu.be/srz4U9RHliQ?list=PLlxHm_Px-Ie1EIRlDHG2lW5H7c2UYvops&t=1010
    """

    # Recommended order of Jamf processors
    rec_order = (
        "com.github.grahampugh.jamf-upload.processors/JamfCategoryUploader",
        "com.github.grahampugh.jamf-upload.processors/JamfExtensionAttributeUploader",
        "com.github.grahampugh.jamf-upload.processors/JamfPackageUploader",
        "com.github.grahampugh.jamf-upload.processors/JamfScriptUploader",
        "com.github.grahampugh.jamf-upload.processors/JamfComputerGroupUploader",
        # TODO: The three below may depend on computer groups, but there's no
        # easy way to ignore relative order if multiple are used. Focusing on
        # JamfPolicyUploader only for now.
        "com.github.grahampugh.jamf-upload.processors/JamfPolicyUploader",
        # "com.github.grahampugh.jamf-upload.processors/JamfComputerProfileUploader",
        # "com.github.grahampugh.jamf-upload.processors/JamfSoftwareRestrictionUploader",
    )

    passed = True
    # All JamfUploader processors in recipe, ignoring duplicates, preserving order.
    actual_order = list(
        dict.fromkeys(
            x.get("Processor") for x in process if x.get("Processor") in rec_order
        )
    )
    desired_order = [x for x in rec_order if x in actual_order]
    if desired_order != actual_order:
        print(
            "{}: WARNING: JamfUploader processors are not in "
            "the recommended order: {}.".format(
                filename,
                ", ".join([x.split("/")[-1] for x in desired_order]),
            )
        )

    return passed


def validate_no_var_in_app_path(process, filename):
    """Ensure %NAME% is not used in app paths that should be hard coded."""

    # Processors for which %NAME%.app should not be present in the arguments.
    no_name_var_in_proc_args = (
        "CodeSignatureVerifier",
        "Versioner",
        "PkgPayloadUnpacker",
        "FlatPkgUnpacker",
        "FileFinder",
        "Copier",
        "AppDmgVersioner",
        "InstallFromDMG",
    )

    passed = True
    for proc in process:
        if proc.get("Processor") in no_name_var_in_proc_args and "Arguments" in proc:
            for _, argvalue in proc["Arguments"].items():
                if isinstance(argvalue, str) and "%NAME%.app" in argvalue:
                    print(
                        f"{filename}: Use actual app name instead of %NAME%.app in {proc.get('Processor')} "
                        "processor argument."
                    )
                    passed = False

    return passed


# For each processor type, this is the list of processors that
# we only expect to see in that type. Tuple keys are all recipe types that share these conventions.
_PROC_TYPE_CONVENTIONS = {
    ("download",): [
        "SparkleUpdateInfoProvider",
        "GitHubReleasesInfoProvider",
        "URLDownloader",
        "URLDownloaderPython",
        "EndOfCheckPhase",
    ],
    ("munki",): [
        "MunkiInfoCreator",
        "MunkiInstallsItemsCreator",
        "MunkiPkginfoMerger",
        "MunkiCatalogBuilder",
        "MunkiSetDefaultCatalog",
        "MunkiOptionalReceiptEditor",
        "MunkiImporter",
    ],
    ("pkg",): ["AppPkgCreator", "PkgCreator"],
    ("install",): ["InstallFromDMG", "Installer"],
    # https://github.com/jssimporter/JSSImporter
    ("jss", "jss-upload"): ["JSSImporter"],
    # https://github.com/grahampugh/jamf-upload
    ("jamf", "jamf-upload", "jamfclirunner"): [
        "com.github.grahampugh.jamf-upload.processors/JamfAccountUploader",
        "com.github.grahampugh.jamf-upload.processors/JamfCategoryUploader",
        "com.github.grahampugh.jamf-upload.processors/JamfClassicAPIObjectUploader",
        "com.github.grahampugh.jamf-upload.processors/JamfComputerGroupDeleter",
        "com.github.grahampugh.jamf-upload.processors/JamfComputerGroupUploader",
        "com.github.grahampugh.jamf-upload.processors/JamfComputerProfileUploader",
        "com.github.grahampugh.jamf-upload.processors/JamfDockItemUploader",
        "com.github.grahampugh.jamf-upload.processors/JamfExtensionAttributeUploader",
        "com.github.grahampugh.jamf-upload.processors/JamfIconUploader",
        "com.github.grahampugh.jamf-upload.processors/JamfMacAppUploader",
        "com.github.grahampugh.jamf-upload.processors/JamfMobileDeviceGroupUploader",
        "com.github.grahampugh.jamf-upload.processors/JamfMobileDeviceProfileUploader",
        "com.github.grahampugh.jamf-upload.processors/JamfPackageCleaner",
        "com.github.grahampugh.jamf-upload.processors/JamfPackageRecalculator",
        "com.github.grahampugh.jamf-upload.processors/JamfPackageUploader",
        "com.github.grahampugh.jamf-upload.processors/JamfPatchChecker",
        "com.github.grahampugh.jamf-upload.processors/JamfPatchUploader",
        "com.github.grahampugh.jamf-upload.processors/JamfPkgMetadataUploader",
        "com.github.grahampugh.jamf-upload.processors/JamfPolicyDeleter",
        "com.github.grahampugh.jamf-upload.processors/JamfPolicyLogFlusher",
        "com.github.grahampugh.jamf-upload.processors/JamfPolicyUploader",
        "com.github.grahampugh.jamf-upload.processors/JamfScriptUploader",
        "com.github.grahampugh.jamf-upload.processors/JamfSoftwareRestrictionUploader",
        "com.github.grahampugh.jamf-upload.processors/JamfUploaderSlacker",
        "com.github.grahampugh.jamf-upload.processors/JamfUploaderTeamsNotifier",
        # https://github.com/grahampugh/recipes (JamfCLIRunner)
        "com.github.grahampugh.recipes.JamfCLIRunner",
    ],
    # https://github.com/autopkg/filewave
    ("filewave",): [
        "com.github.autopkg.filewave.FWTool/FileWaveImporter",
        "com.github.johncclayton.filewave.FWTool/FileWaveImporter",
        "com.github.autopkg.filewave.FWTool/FWTool",
    ],
    ("verify",): ["com.github.n8felton.shared/GPGSignatureVerifier"],
    # https://github.com/almenscorner/intune-upload
    ("intune",): [
        "com.github.almenscorner.intune-upload.processors/IntuneAppUploader",
        "com.github.almenscorner.intune-upload.processors/IntuneAppIconGetter",
    ],
    # https://github.com/fleetdm/fleet
    ("fleet",): ["com.github.fleet.FleetImporter/FleetImporter"],
    # https://github.com/codeskipper/WorkSpaceOneImporter
    ("ws1",): [
        "com.github.codeskipper.VMWARE-WorkSpaceOneImporter/WorkSpaceOneImporter"
    ],
}

_ALL_KNOWN_RECIPE_TYPES = [
    f".{recipe_type}."
    for recipe_group in _PROC_TYPE_CONVENTIONS
    for recipe_type in recipe_group
]


def validate_proc_type_conventions(process, filename):
    """Ensure that processors used align with recipe type conventions."""

    if not any(known_type in filename for known_type in _ALL_KNOWN_RECIPE_TYPES):
        print(
            f"{filename}: WARNING: Unknown recipe type. Skipping processor convention checks."
        )
        return True

    passed = True
    processors = [x.get("Processor") for x in process]
    for recipe_group in _PROC_TYPE_CONVENTIONS:
        type_hints = [f".{recipe_type}." for recipe_type in recipe_group]
        if not any(th in filename for th in type_hints):
            for processor in processors:
                if processor in _PROC_TYPE_CONVENTIONS[recipe_group]:
                    print(
                        f"{filename}: Processor {processor} is not conventional for this "
                        "recipe type."
                    )
                    passed = False

    return passed


def validate_required_proc_for_types(process, filename):
    """Ensure that certain recipe types always have specific processors."""

    # For each recipe type, this is the list of processors that
    # MUST exist in that type. Uses "OR" logic, not "AND."
    required_proc_for_type = {
        # Skipping EndOfCheckPhase because validate_endofcheckphase()
        # already tests this.
        # "download": ["EndOfCheckPhase"],
        "munki": ["MunkiImporter"],
        "pkg": ["AppPkgCreator", "PkgCreator", "PkgCopier"],
        "install": ["InstallFromDMG", "Installer"],
        # https://github.com/jssimporter/JSSImporter
        "jss": ["JSSImporter"],
        # https://github.com/autopkg/filewave
        "filewave": ["com.github.autopkg.filewave.FWTool/FileWaveImporter"],
        # https://derflounder.wordpress.com/2021/07/30/signing-autopkg-built-packages-using-a-sign-recipe/
        "sign": ["com.github.rtrouton.SharedProcessors/PkgSigner"],
        "verify": ["com.github.n8felton.shared/GPGSignatureVerifier"],
    }

    passed = True
    processors = [x.get("Processor") for x in process]
    for recipe_type in required_proc_for_type:
        req_procs = required_proc_for_type[recipe_type]
        type_hint = f".{recipe_type}."
        if type_hint in filename:
            if recipe_type == "pkg" and processors == []:
                # OK for pkg recipes to have an empty process list, as long as
                # their parent is a download recipe that produces a pkg.
                # TODO: Validate parent is a download recipe.
                break
            if not any(x in processors for x in req_procs):
                if len(req_procs) == 1:
                    print(
                        f"{filename}: Recipe type {recipe_type} should contain processor "
                        f"{req_procs[0]}."
                    )
                else:
                    print(
                        f"{filename}: Recipe type {recipe_type} should contain one of these "
                        f"processors: {req_procs}."
                    )
                passed = False

    return passed


def validate_proc_args(process, filename):
    """Warn if invalid processor arguments are used."""

    passed = True

    # List of argument names (lowercase) that will not be flagged as invalid.
    ignored_args = ("note", "notes", "comment", "comments")

    for proc in process:
        if proc["Processor"] not in _CORE_PROCS:
            # Skip input variable validation for non-core processors.
            continue
        for arg in proc.get("Arguments", {}):
            if arg.lower() in ignored_args:
                # Skip args in ignored list above.
                continue

            suggestion = (
                "Consider using the VariableSetter processor (AutoPkg 2.9.0+) to set "
                "custom environment variables."
            )
            if not _CORE_PROCS[proc["Processor"]]:
                print(
                    f"{filename}: Unknown argument {arg} for processor {proc['Processor']}, "
                    "which does not accept any arguments."
                )
                print(suggestion)
                passed = False
            elif arg not in _CORE_PROCS[proc["Processor"]]:
                print(
                    f"{filename}: Unknown argument {arg} for processor {proc['Processor']}. Allowed arguments are: "
                    + ", ".join(_CORE_PROCS[proc["Processor"]])
                )
                print(suggestion)
                passed = False

    return passed


def main(argv=None):
    """Main process."""

    # Parse command line arguments.
    argparser = build_argument_parser()
    args = argparser.parse_args(argv)
    if args.strict:
        args.ignore_min_vers_before = "0.1.0"

    # Track identifiers we've seen.
    seen_identifiers = []

    retval = 0
    for filename in args.filenames:
        recipe = load_autopkg_recipe(filename)
        if not recipe:
            retval = 1
            break  # No need to continue checking this file

        # Top level keys that all AutoPkg recipes should contain.
        # TODO: Make required recipe keys configurable.
        required_keys = ["Identifier"]
        if not validate_required_keys(recipe, filename, required_keys):
            retval = 1
            break  # No need to continue checking this file

        # Ensure the recipe identifier isn't duplicated.
        if recipe["Identifier"] in seen_identifiers:
            print(
                f'{filename}: Identifier "{recipe["Identifier"]}" is shared by another recipe in this repo.'
            )
            retval = 1
        else:
            seen_identifiers.append(recipe["Identifier"])

        # Validate identifiers.
        if "Process" not in recipe:
            if not validate_recipe_prefix(recipe, filename, args.override_prefix):
                retval = 1
        if "Process" in recipe:
            if not validate_recipe_prefix(recipe, filename, args.recipe_prefix):
                retval = 1
        if recipe["Identifier"] == recipe.get("ParentRecipe"):
            print(f"{filename}: Identifier and ParentRecipe should not be the same.")
            retval = 1

        # If the Input key contains a pkginfo dict, make a best effort to validate its contents.
        input_key = recipe.get("Input", recipe.get("input", recipe.get("INPUT")))
        if input_key and "pkginfo" in input_key:

            # Check for presence of required pkginfo keys.
            # TODO: Make required pkginfo keys within a recipe configurable.
            req_keys = ["name", "description"]
            if not validate_required_keys(input_key["pkginfo"], filename, req_keys):
                retval = 1

            # Ensure pkginfo keys have expected types.
            if not validate_pkginfo_key_types(input_key["pkginfo"], filename):
                retval = 1

            # Validate RestartAction key.
            if not validate_restart_action_key(input_key["pkginfo"], filename):
                retval = 1

            # Validate uninstall method.
            if not validate_uninstall_method(input_key["pkginfo"], filename):
                retval = 1

            # Validate supported architectures.
            if not validate_supported_architectures(
                input_key["pkginfo"], filename, recipe_mode=True
            ):
                retval = 1

            # Check for deprecated pkginfo keys.
            if not detect_deprecated_keys(input_key["pkginfo"], filename):
                retval = 1

            # Check for common mistakes in key names.
            if not detect_typoed_keys(input_key["pkginfo"], filename):
                retval = 1

            # TODO: Additional pkginfo checks here.

        # Warn about comments that would be lost during `plutil -convert xml1`
        if not validate_comments(filename, args.strict):
            retval = 1

        # Processor checks.
        if "Process" in recipe:
            process = recipe["Process"]

            if not validate_processor_keys(process, filename):
                retval = 1

            if not validate_endofcheckphase(process, filename):
                retval = 1

            if not validate_no_var_in_app_path(process, filename):
                retval = 1

            min_vers = recipe.get("MinimumVersion")
            if min_vers and not validate_minimumversion(
                process, min_vers, args.ignore_min_vers_before, filename
            ):
                retval = 1

            if not validate_no_deprecated_procs(process, filename):
                retval = 1

            if not validate_no_superclass_procs(process, filename):
                retval = 1

            if not validate_jamf_processor_order(process, filename):
                retval = 1

            if HAS_AUTOPKGLIB:
                if not validate_proc_args(process, filename):
                    retval = 1

            if args.strict:
                if not validate_proc_type_conventions(process, filename):
                    retval = 1

                if not validate_required_proc_for_types(process, filename):
                    retval = 1

    return retval


if __name__ == "__main__":
    exit(main())
